cabal-version: 3.4

name:           with
version:        0.1.0.0
description:    Please see the README on GitHub at <https://github.com/wasabi315/with#readme>
homepage:       https://github.com/wasabi315/with#readme
bug-reports:    https://github.com/wasabi315/with/issues
author:         Satoshi Takimoto
maintainer:     wasabi.nvim.st@gmail.com
copyright:      2026 Satoshi Takimoto
license:        BSD-3-Clause
license-file:   LICENSE
build-type:     Simple
extra-source-files:
    README.md
    CHANGELOG.md

source-repository head
  type: git
  location: https://github.com/wasabi315/with

library
  exposed-modules:
    With
    With.Internal
  hs-source-dirs: src
  build-depends: base >=4.15 && <5
  default-language: Haskell2010
  ghc-options: -O2

executable with-example
  hs-source-dirs: example
  main-is: Main.hs
  default-language: Haskell2010
  build-depends:
    , base >= 4.15 && <5
    , with

test-suite with-inspect
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  default-language: Haskell2010
  ghc-options: -O2
  build-depends:
    , base >= 4.15 && <5
    , inspection-testing
    , with
